version: '2'
volumes:
  dbvolume:
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dunya
      POSTGRES_DB: dunya
    volumes:
      - dbvolume:/var/lib/postgresql/data/

  redis:
    image: redis

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=dunya
      - RABBITMQ_DEFAULT_PASS=dunyapassword
      - RABBITMQ_DEFAULT_VHOST=dunya
  web:
    build: .
    command: dumb-init python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./media:/media/
      - ./tmp:/tmp/
      - /data/incoming:/incoming
      - ${PYCOMPMUSIC_LOC}:/sources/pycompmusic/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - environment
  # All celery hosts should listen on a queue of the same name as their host/name (-Q and -n)
  celeryimport:
    build: .
    command: celery worker --app dunya -l info -Q import,celeryimport -n celeryimport
    volumes:
      - .:/code
      - /data/incoming:/incoming
      - ${PYCOMPMUSIC_LOC}:/sources/pycompmusic/
    env_file:
      - environment
    depends_on:
      - rabbitmq
      - db
      - redis
  celeryprocess:
    build: .
    command: celery worker --app dunya -l info -Q celery,celeryprocess -n celeryprocess
    volumes:
      - .:/code
      - /data/incoming:/incoming
      - ${PYCOMPMUSIC_LOC}:/sources/pycompmusic/
    env_file:
      - environment
    depends_on:
      - rabbitmq
      - db
      - redis
