version: '2'
services:
  db:
    image: postgres
  redis:
    image: redis
  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=dunya
      - RABBITMQ_DEFAULT_PASS=dunyapassword
      - RABBITMQ_DEFAULT_VHOST=dunya
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./media:/media/
      - ./tmp:/tmp/
    ports:
      - "8000:8000"
    depends_on:
      - db
  celeryimport:
    build: .
    command: celery worker --app dunya -l info -Q import -n celeryimport
  celeryprocess:
    build: .
    command: celery worker --app dunya -l info -Q celery -n celeryprocess
